#!/bin/bash

sudo yum update -y
yum install dkms gcc make kernel-devel bzip2 binutils patch libgomp glibc-headers glibc-devel kernel-headers -y
sudo mkdir -p /media/cdrom
sudo mount /dev/sr0 /media/cdrom
sudo sh /media/cdrom/VBoxLinuxAdditions.run
sudo usermod -aG vboxsf $USER
