#!/bin/bash

sudo apt-get update
sudo apt-get install dkms build-essential linux-headers-$(uname -r) -y
sudo mkdir -p /media/cdrom
sudo mount /dev/sr0 /media/cdrom
sudo sh /media/cdrom/VBoxLinuxAdditions.run
sudo usermod -aG vboxsf $USER
